enum BAD_REQUEST_ERROR_CODES {
  REQ_BODY_VALIDATION_FAILED = '400X1',
  REQ_PRE_VALIDATION_FAILED = '400X2',
}

enum UNAUTHORIZED_ERROR_CODES {
  INVALID_AUTH_TOKEN = '401X1',
  MISSING_AUTH_TOKEN = '401X2',
}

enum FORBIDDEN_ERROR_CODES {
  INSUFFICIENT_ACCESS = '403X1',
}

export const CUSTOM_ERROR_CODES = {
  ...BAD_REQUEST_ERROR_CODES,
  ...UNAUTHORIZED_ERROR_CODES,
  ...FORBIDDEN_ERROR_CODES,
};

export type CUSTOM_ERROR_CODE =
  | BAD_REQUEST_ERROR_CODES
  | UNAUTHORIZED_ERROR_CODES
  | FORBIDDEN_ERROR_CODES;
